### ISSUE TITLE
drop underscore

### ISSUE THREAD

**Issue by stoeffel** [bylexus/protobone#10]
Is there a need for underscore? Or could it be solved using prototypes stuff?

**Comment by stoeffel** [comment]
btw underscore gets bundled into the browserified file (sice)

**Comment by bylexus** [comment]
Right. I had that before, but included underscore out of pure lazyness. I will remove it in the next bugfix release.

**Comment by stoeffel** [comment]
:balloon:

**Comment by bylexus** [comment]
dropped in 0.0.4: only Prototype methods are used.

**Comment by stoeffel** [comment]
:100:
